name: task
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  firebase_core: ^2.3.0
  bloc: ^8.1.0
  google_sign_in: ^5.4.2
  flutter_facebook_auth: ^5.0.6
  firebase_auth: ^4.1.3
  flutter_native_splash: ^2.2.15
  flutter_svg: ^1.1.6
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
flutter_native_splash:

  color: "#FFFFFF"
  image: assets/images/app_logo.png
  color_dark: "#FFFFFF"
  image_dark: assets/images/app_logo.png
  android_12:
    image: assets/images/app_logo.png
  # Splash screen background color.
    color: "#FFFFFF"
  # App icon background color.
    icon_background_color: "#eeeeee"
  android: true
  ios: true
  fullscreen: true

  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf

    - family: Light
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf

    - family: Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf      

